apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: omnipod
spec:
  ports:
    - port: 5432
  selector:
    app: omnipod
    tier: postgres
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: omnipod
spec:
  selector:
    matchLabels:
      app: omnipod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: omnipod
        tier: postgres
    spec:
      containers:
        - image: postgres:9.5.3
          name: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: password1234
            - name: POSTGRES_USER
              value: omnipod
            - name: POSTGRES_DB
              value: omnipod_production
            #- name: PGDATA
             # value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
              name: postgres
          #volumeMounts:
           # - name: postgres-persistent-storage
            #  mountPath: /var/lib/postgresql/data
      #volumes:
       # - name: postgres-persistent-storage
        #  awsElasticBlockStore:
         #   volumeID: vol-0863077e9cc9b8523
          #  fsType: ext4
